require("core.commands.replace")
require("core.commands.tmux")
require("core.commands.relpath")
require("core.commands.copy_filename")
require("core.commands.copy_project_root")
require("core.commands.scratch")
require("core.commands.trim_trailing_ws")
require("core.commands.toggle_relnum")
require("core.commands.reload_config")
require("core.commands.buf_only")
require("core.commands.ime")
-- require("core.commands.buffer")
