bind-key s display-popup \
  -d "#{pane_current_path}" \
  -w 60% \
  -h 60% \
  -E "$HOME/.local/bin/tmux-select-session"

bind-key w display-popup \
  -d "#{pane_current_path}" \
  -w 60% \
  -h 60% \
  -E "$HOME/.local/bin/tmux-select-window"

bind-key g display-popup \
  -d "#{pane_current_path}" \
  -w 95% \
  -h 95% \
  -E "lazygit -ucd ~/.config/lazygit"

bind-key d display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazydocker"

bind-key c display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "claude"

# NOTE: tmux popup は passthrough 非対応のため yazi の TRT が発生する (tmux#4329, yazi#2308)。
# 入れ子の tmux セッションを popup 内で立て、その中で yazi を起動することで回避する。
bind-key y display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "tmux new-session yazi \\; set status off"

bind-key v display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "nvim"

bind-key z display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "$SHELL"

unbind f
