##### 基本 #####
set -g focus-events on

##### 基本設定ファイル（キーバインド、マウス、表示など） #####
run-shell 'for f in "$HOME"/.tmux/common/configs/*.tmux; do [ -f "$f" ] && tmux source-file "$f"; done'

##### セッション定義を読み込み #####
run-shell "$HOME/.tmux/personal/scripts/run-all.sh"